#app
server:
    port: 8080
    context-path: /

cloud:
    server:
        port: 8090
        host: gateway.wookitech.com
#        host: platform1.wookitech.com
dbpwd: Ugrtbx*6$#
isPro: false
#spring
spring:
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .html
  mvc:
    static-path-pattern: /**
  devtools: true
  # mysql DATABASE CONFIG
  datasource:
      name: aims
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://rm-wz936o7nysnexzz7s.mysql.rds.aliyuncs.com:3306/wookitech
      username: root
      password:
      type: com.alibaba.druid.pool.DruidDataSource
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      spring.datasource.filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      #useGlobalDataSourceStat: true
  redis:
      database: 0
      # Redis server host.
      host: 127.0.0.1
#      host: 192.168.1.108
      port: 6379
      password: 123456
#      timeout: 10000
      timeout: 0
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
    #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.wooki.system.**.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义填充策略接口实现
#    meta-data-handler: com.crhc.core.common.mybatis.MyMetaObjectHandler
    #自定义SQL注入器
#    sql-injector: com.crhc.core.common.mybatis.MySqlInjector
    sql-injector: com.baomidou.mybatisplus.mapper.PostgreSqlInjector

  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
#    logPrefix: mapper.

# picture

#logging
logging:
  level: INFO
#  config: classpath:log4j2-analy.xml
  path: /users/user/desktop
#  path: /home/log

lock-platform:
  url: https://www.doormaster.me:9099
  lock-list: /doormaster/server/devices
  temp-pwd: /doormaster/server/devices/temp_pwd
  method:
    get: GET
    add: POST
    delete: DELETE
  encode: utf-8

application:
  aliAccessKeyId: LTAISDF2x3AEd8Io
  accessKeySecret: xSVcJbBCeqH5boNVnW8KT6QEaGrAqH
  endPoint: oss-cn-shenzhen.aliyuncs.com
  bucketName: wookiqrcode
  picturePrefix: http://wookiqrcode.oss-cn-shenzhen.aliyuncs.com/







